# Generated by Django 5.0.6 on 2024-05-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0003_alter_userdata_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('jti', models.CharField(max_length=100)),
            ],
        ),
    ]
